Repository codestates-seb/seb41_main_025, pull requests merged in 2023-01, with the labels that each got.

#18 Feat/be jwt
  server/build.gradle
  server/src/main/java/com/mainProject/server/domain/board/eneity/Board.java
  server/src/main/java/com/mainProject/server/domain/comment/dto/CommentDto.java
  server/src/main/java/com/mainProject/server/domain/comment/entity/Comment.java
  server/src/main/java/com/mainProject/server/domain/comment/mapper/CommentMapper.java
  server/src/main/java/com/mainProject/server/domain/comment/service/CommentService.java
  server/src/main/java/com/mainProject/server/domain/content/controller/CrawlingController.java
  server/src/main/java/com/mainProject/server/domain/content/entity/Content.java
  server/src/main/java/com/mainProject/server/domain/content/service/ContentService.java
  server/src/main/java/com/mainProject/server/domain/content/service/CrawlingService.java
  server/src/main/java/com/mainProject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainProject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainProject/server/domain/member/service/MemberService.java
  server/src/main/java/com/mainProject/server/global/auth/authority/CustomAuthorityUtils.java
  server/src/main/java/com/mainProject/server/global/auth/authority/ErrorResponder.java
  server/src/main/java/com/mainProject/server/global/auth/config/SecurityConfiguration.java
  server/src/main/java/com/mainProject/server/global/auth/dto/LoginDto.java
  server/src/main/java/com/mainProject/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainProject/server/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainProject/server/global/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/mainProject/server/global/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/mainProject/server/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/mainProject/server/global/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/mainProject/server/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/mainProject/server/global/auth/userDetails/MemberDetailsService.java
  server/src/main/java/com/mainProject/server/global/exception/ExceptionCode.java
  server/src/main/resources/application.yml
Labels: BE_강신찬, BE_박금비, BE_김희진, ✨ feat

#23 Feat/be crawling
  server/src/main/java/com/mainProject/server/domain/content/entity/Choice.java
  server/src/main/java/com/mainProject/server/domain/content/entity/Content.java
  server/src/main/java/com/mainProject/server/domain/content/entity/Deprecated.java
  server/src/main/java/com/mainProject/server/domain/content/entity/Favorite.java
  server/src/main/java/com/mainProject/server/domain/content/entity/Ott.java
  server/src/main/java/com/mainProject/server/domain/content/entity/Recommend.java
  server/src/main/java/com/mainProject/server/domain/content/service/ContentService.java
  server/src/main/java/com/mainProject/server/domain/content/service/CrawlingService.java
  server/src/main/java/com/mainProject/server/domain/member/entity/Member.java
Labels: BE_강신찬, BE_박금비, BE_김희진, ✨ feat

#55 ✨ feat: get mapping modify
  server/src/main/java/com/mainProject/server/domain/choice/mapper/ChoiceMapper.java
  server/src/main/java/com/mainProject/server/domain/favorite/mapper/FavoriteMapper.java
  server/src/main/java/com/mainProject/server/domain/recommend/mapper/RecommendMapper.java
Labels: BE_강신찬, BE_박금비, BE_김희진, ✨ feat

#57 Feat/be create get
  server/build.gradle
  server/src/main/java/com/mainProject/server/ServerApplication.java
  server/src/main/java/com/mainProject/server/domain/choice/controller/ChoiceController.java
  server/src/main/java/com/mainProject/server/domain/content/controller/CrawlingController.java
  server/src/main/java/com/mainProject/server/domain/content/service/CrawlingService.java
  server/src/main/java/com/mainProject/server/domain/recommend/controller/RecommendController.java
  server/src/main/java/com/mainProject/server/domain/recommend/service/RecommendService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: BE_강신찬, BE_박금비, BE_김희진

#58 ✨ feat:logout
  server/src/main/java/com/mainProject/server/global/auth/config/SecurityConfiguration.java
  server/src/main/java/com/mainProject/server/global/auth/config/WebConfig.java
  server/src/main/java/com/mainProject/server/global/auth/handler/MembersLogoutHandler.java
  server/src/main/java/com/mainProject/server/global/auth/handler/MembersLogoutSuccessHandler.java
Labels: BE_강신찬, BE_박금비, BE_김희진, ✨ feat

#63 ✨ feat: login
  server/src/main/java/com/mainProject/server/global/auth/dto/Principal.java
  server/src/main/java/com/mainProject/server/global/auth/handler/MemberAuthenticationSuccessHandler.java
Labels: BE_강신찬, BE_박금비, BE_김희진, ✨ feat

#82 ✨ feat: 마이페이지
  server/src/main/java/com/mainProject/server/domain/choice/controller/ChoiceController.java
  server/src/main/java/com/mainProject/server/domain/choice/dto/ChoiceResponseDto.java
  server/src/main/java/com/mainProject/server/domain/choice/mapper/ChoiceMapper.java
  server/src/main/java/com/mainProject/server/domain/choice/service/ChoiceService.java
  server/src/main/java/com/mainProject/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/mainProject/server/domain/content/dto/ContentResponseMinDto.java
  server/src/main/java/com/mainProject/server/domain/content/entity/Content.java
  server/src/main/java/com/mainProject/server/domain/favorite/controller/FavoriteController.java
  server/src/main/java/com/mainProject/server/domain/favorite/dto/FavoriteResponseDto.java
  server/src/main/java/com/mainProject/server/domain/favorite/mapper/FavoriteMapper.java
  server/src/main/java/com/mainProject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainProject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainProject/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/mainProject/server/domain/member/service/MemberService.java
  server/src/main/java/com/mainProject/server/domain/recommend/controller/RecommendController.java
  server/src/main/java/com/mainProject/server/domain/recommend/dto/RecommendDto.java
  server/src/main/java/com/mainProject/server/domain/recommend/mapper/RecommendMapper.java
  server/src/main/java/com/mainProject/server/domain/recommend/service/RecommendService.java
Labels: BE_강신찬, BE_박금비, BE_김희진

#83 🐛 fix: 크롤링 속도 개선
  server/src/main/java/com/mainProject/server/domain/content/service/CrawlingService.java
Labels: BE_강신찬

#93 ✨ feat: login
  server/src/main/java/com/mainProject/server/domain/member/service/MemberService.java
Labels: BE_강신찬, BE_박금비, BE_김희진

#100 ✨ feat: board order
  server/src/main/java/com/mainProject/server/domain/board/service/BoardService.java
Labels: BE_강신찬, BE_박금비, BE_김희진, ✨ feat

#101 ♻️ refactor: add delete, add ott list
  server/src/main/java/com/mainProject/server/domain/choice/controller/ChoiceController.java
  server/src/main/java/com/mainProject/server/domain/choice/service/ChoiceService.java
  server/src/main/java/com/mainProject/server/domain/content/controller/ContentController.java
  server/src/main/java/com/mainProject/server/domain/content/dto/ContentResponseDto.java
  server/src/main/java/com/mainProject/server/domain/content/entity/Content.java
  server/src/main/java/com/mainProject/server/domain/content/service/CrawlingService.java
  server/src/main/java/com/mainProject/server/domain/recommend/controller/RecommendController.java
  server/src/main/java/com/mainProject/server/domain/recommend/service/RecommendService.java
  server/src/main/java/com/mainProject/server/global/response/DoubleResponseDto.java
Labels: BE_강신찬, BE_박금비, BE_김희진, ♻️ refactor

#103 ✨ feat: s3 img
  server/build.gradle
  server/src/main/java/com/mainProject/server/ServerApplication.java
  server/src/main/java/com/mainProject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainProject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainProject/server/domain/member/service/MemberService.java
  server/src/main/java/com/mainProject/server/domain/recommend/service/RecommendService.java
  server/src/main/java/com/mainProject/server/global/auth/config/S3Config.java
  server/src/main/java/com/mainProject/server/global/upload/S3UploadService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
Labels: BE_강신찬, BE_박금비, BE_김희진, ✨ feat

#105 🐛 fix: 멤버 사진 저장
  server/src/main/java/com/mainProject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainProject/server/domain/member/service/MemberService.java
  server/src/main/java/com/mainProject/server/global/upload/S3UploadService.java
Labels: BE_강신찬, BE_박금비, BE_김희진

#108 ♻️ refactor: content add local time
  server/.gitignore
  server/src/main/java/com/mainProject/server/domain/content/dto/ContentResponseDto.java
  server/src/main/resources/application-server.yml
Labels: BE_강신찬, BE_박금비, BE_김희진, ♻️ refactor
